Make hydra-check consider all platforms (#23)

diff --git a/.github/workflows/health-check.yml b/.github/workflows/health-check.yml
--- a/.github/workflows/health-check.yml
+++ b/.github/workflows/health-check.yml
@@ -12,8 +12,23 @@ jobs:
     timeout-minutes: 30
     steps:
       - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
-      - run: |
-          nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#hydra-check' -- '${{ inputs.pname }}'
+      # Using `--eval` to check all platforms. See https://github.com/nix-community/hydra-check/issues/91
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - name: Run hydra-check
+        run: |
+          nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#hydra-check' -- --json --channel=nixpkgs-unstable --eval \
+            '${{ inputs.pname }}' | tee raw.json
+      - name: Normalize the result
+        run: |
+          jq --from-file normalize-hydra-eval.jq raw.json | tee normalized.json
+      - name: Check and report if found errors
+        run: |
+          if jq -e '.[] | select(.severity == "error")' normalized.json > errors.jsonl; then
+            cat errors.jsonl
+            exit 1
+          fi
 
   nixpkgs-update:
     runs-on: ubuntu-24.04
